apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: pip
  labels:
    product_pip-clients-home-app: "true"
  name: pip-clients-home-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        product_pip-clients-home-app: "true"
    spec:
      containers:
      - image: pipregistry.azurecr.io/pip-clients/pip-clients-home-app:1.0.0-1-rc
        name:  pip-clients-home
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets:
      - name: azure-container-registry-access
---
kind: Service
apiVersion: v1
metadata:
  name: pip-clients-home-service
  namespace: pip
  labels:
    product_pip-clients-home-app: "true"
spec:
  selector:
    product_pip-clients-home-app: "true"
  ports:
    - port: 80
